### Create Group
POST http://localhost:3000/groups
Content-Type: application/json
Accept: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1ODY1MDQwMiwiZXhwIjoxNjU4NjU0MDAyfQ.73GZW_qSMJx2xE_M-yPzWqMvuVjfMBom-r0ElNsKk9s

{
  "name": "Noob",
  "cover": null
}
