### Login
POST http://localhost:3000/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "fafnur@yandex.ru",
  "password": "123456"
}

### Wrong login
POST http://localhost:3000/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "guest",
  "password": "123456"
}

### Reset
POST http://localhost:3000/auth/reset?backUrl=http://localhost:4200
Content-Type: application/json
Accept: application/json

{
  "email": "fafnur@yandex.ru"
}

### Register
POST http://localhost:3000/auth/register
Content-Type: application/json
Accept: application/json


{
  "firstname": "Ivan2",
  "lastname": "Groot",
  "email": "ff@sws.wrt",
  "password": "123456"
}


### Confirm email
GET http://localhost:3000/auth/confirm/163e916f64
Content-Type: application/json
Accept: application/json

