### Create card with group
POST http://localhost:3000/cards
Content-Type: application/json
Accept: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1ODY0MTU5OCwiZXhwIjoxNjU4NjQ1MTk4fQ.n8lrB0AQx1Rwz7t51OBQ1ehavJrOkNYYgq9148FV6FE

{
  "original": "Monkey",
  "translation": "Обезьяна",
  "group": 2
}
