### Create Group
POST http://localhost:3000/card-groups
Content-Type: application/json
Accept: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1NzY3MzY4MCwiZXhwIjoxNjU3Njc3MjgwfQ.C63aEiZDPDEyAC6oAPvbFosRgDVWDYzMDRNJNNVyrpc

{
  "name": "Simple Group",
  "cover": null
}
